#!/usr/bin/env python3
"""Fail-closed content gate for xv6 guest scanout and the host SDL window.

The xv6 framebuffer boot logo is deliberately non-black and has enough color
variance to pass generic screenshot checks.  This gate recognizes that exact
palette/layout as stale boot content and requires the deterministic Qt Wayland
smoke surface in *both* independently captured images.

The Qt surface is generated by /opt/xv6-kde/qt-wayland-smoke.qml.  Its 420x260
background alternates between #1c7ed6 and #2f9e44.  Requiring a large connected
region near either color tolerates SDL scaling and host color conversion while
remaining independent of window placement and animation phase.
"""

from __future__ import annotations

import argparse
from collections import deque
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any


SENTINEL_COLORS = {
    "blue": (0x1C, 0x7E, 0xD6),
    "green": (0x2F, 0x9E, 0x44),
}

BOOT_COLORS = {
    "background": (10, 22, 38),
    "panel": (15, 35, 58),
    "title": (116, 198, 255),
    "accent": (86, 230, 170),
}


class GateInputError(RuntimeError):
    pass


def _next_ppm_token(data: bytes, offset: int) -> tuple[bytes, int]:
    length = len(data)
    while offset < length:
        byte = data[offset]
        if byte in b" \t\r\n":
            offset += 1
            continue
        if byte == ord("#"):
            newline = data.find(b"\n", offset)
            if newline < 0:
                raise GateInputError("unterminated PPM header comment")
            offset = newline + 1
            continue
        break
    start = offset
    while offset < length and data[offset] not in b" \t\r\n#":
        offset += 1
    if start == offset:
        raise GateInputError("truncated PPM header")
    return data[start:offset], offset


def _decode_ppm(data: bytes, source: str) -> tuple[int, int, bytes]:
    magic, offset = _next_ppm_token(data, 0)
    width_token, offset = _next_ppm_token(data, offset)
    height_token, offset = _next_ppm_token(data, offset)
    maxval_token, offset = _next_ppm_token(data, offset)
    try:
        width = int(width_token)
        height = int(height_token)
        maxval = int(maxval_token)
    except ValueError as error:
        raise GateInputError(f"{source}: invalid PPM dimensions") from error
    if width <= 0 or height <= 0:
        raise GateInputError(f"{source}: non-positive PPM dimensions")
    if width * height > 100_000_000:
        raise GateInputError(f"{source}: unreasonable PPM dimensions")
    if not 0 < maxval <= 65535:
        raise GateInputError(f"{source}: unsupported PPM maxval={maxval}")

    sample_count = width * height * 3
    if magic == b"P6":
        if offset >= len(data) or data[offset] not in b" \t\r\n":
            raise GateInputError(f"{source}: missing PPM raster separator")
        if data[offset : offset + 2] == b"\r\n":
            offset += 2
        else:
            offset += 1
        sample_bytes = 1 if maxval < 256 else 2
        expected_bytes = sample_count * sample_bytes
        raster = data[offset : offset + expected_bytes]
        if len(raster) != expected_bytes:
            raise GateInputError(
                f"{source}: truncated PPM raster expected={expected_bytes} "
                f"got={len(raster)}"
            )
        if sample_bytes == 1 and maxval == 255:
            return width, height, raster
        pixels = bytearray(sample_count)
        if sample_bytes == 1:
            for index, sample in enumerate(raster):
                pixels[index] = (sample * 255 + maxval // 2) // maxval
        else:
            for index in range(sample_count):
                offset = index * 2
                sample = (raster[offset] << 8) | raster[offset + 1]
                pixels[index] = (sample * 255 + maxval // 2) // maxval
        return width, height, bytes(pixels)

    if magic == b"P3":
        values = bytearray()
        for _ in range(sample_count):
            token, offset = _next_ppm_token(data, offset)
            try:
                value = int(token)
            except ValueError as error:
                raise GateInputError(f"{source}: invalid P3 sample") from error
            if not 0 <= value <= maxval:
                raise GateInputError(f"{source}: P3 sample outside 0..{maxval}")
            values.append((value * 255 + maxval // 2) // maxval)
        return width, height, bytes(values)

    raise GateInputError(f"{source}: unsupported image magic {magic!r}")


def _load_image(path: Path) -> tuple[int, int, bytes]:
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise GateInputError(f"{path}: cannot read image: {error}") from error
    if raw.startswith((b"P6", b"P3")):
        return _decode_ppm(raw, str(path))

    convert = shutil.which("convert")
    if convert is None:
        raise GateInputError(
            f"{path}: non-PPM input requires ImageMagick's convert"
        )
    try:
        result = subprocess.run(
            [
                convert,
                str(path),
                "-alpha",
                "off",
                "-colorspace",
                "sRGB",
                "-depth",
                "8",
                "ppm:-",
            ],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise GateInputError(f"{path}: image conversion failed: {error}") from error
    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", "replace").strip()
        raise GateInputError(
            f"{path}: image conversion rc={result.returncode}: {detail}"
        )
    return _decode_ppm(result.stdout, f"converted {path}")


def _near(r: int, g: int, b: int, color: tuple[int, int, int], tolerance: int) -> bool:
    return (
        abs(r - color[0]) <= tolerance
        and abs(g - color[1]) <= tolerance
        and abs(b - color[2]) <= tolerance
    )


def _largest_component(
    pixels: bytes,
    width: int,
    height: int,
    color: tuple[int, int, int],
    tolerance: int,
) -> dict[str, Any]:
    total = width * height
    mask = bytearray(total)
    matched = 0
    for pixel in range(total):
        offset = pixel * 3
        if _near(
            pixels[offset],
            pixels[offset + 1],
            pixels[offset + 2],
            color,
            tolerance,
        ):
            mask[pixel] = 1
            matched += 1

    largest_count = 0
    largest_box = (0, 0, -1, -1)
    scan = 0
    needle = b"\x01"
    while True:
        start = mask.find(needle, scan)
        if start < 0:
            break
        mask[start] = 0
        queue: deque[int] = deque([start])
        count = 0
        min_x = max_x = start % width
        min_y = max_y = start // width
        while queue:
            current = queue.popleft()
            count += 1
            x = current % width
            y = current // width
            if x < min_x:
                min_x = x
            if x > max_x:
                max_x = x
            if y < min_y:
                min_y = y
            if y > max_y:
                max_y = y

            if x > 0:
                neighbor = current - 1
                if mask[neighbor]:
                    mask[neighbor] = 0
                    queue.append(neighbor)
            if x + 1 < width:
                neighbor = current + 1
                if mask[neighbor]:
                    mask[neighbor] = 0
                    queue.append(neighbor)
            if y > 0:
                neighbor = current - width
                if mask[neighbor]:
                    mask[neighbor] = 0
                    queue.append(neighbor)
            if y + 1 < height:
                neighbor = current + width
                if mask[neighbor]:
                    mask[neighbor] = 0
                    queue.append(neighbor)

        if count > largest_count:
            largest_count = count
            largest_box = (min_x, min_y, max_x, max_y)
        scan = start + 1

    min_x, min_y, max_x, max_y = largest_box
    component_width = max_x - min_x + 1 if max_x >= min_x else 0
    component_height = max_y - min_y + 1 if max_y >= min_y else 0
    box_area = component_width * component_height
    fill = largest_count / box_area if box_area else 0.0
    return {
        "matched_pixels": matched,
        "component_pixels": largest_count,
        "component_x": min_x,
        "component_y": min_y,
        "component_width": component_width,
        "component_height": component_height,
        "component_fill": fill,
    }


def _sentinel_result(
    pixels: bytes,
    width: int,
    height: int,
    tolerance: int,
) -> dict[str, Any]:
    total = width * height
    min_pixels = max(2_048, min(10_000, int(total * 0.008)))
    min_width = max(64, min(180, int(width * 0.10)))
    min_height = max(48, min(100, int(height * 0.08)))
    candidates: dict[str, dict[str, Any]] = {}
    for name, color in SENTINEL_COLORS.items():
        candidate = _largest_component(pixels, width, height, color, tolerance)
        left = candidate["component_x"]
        top = candidate["component_y"]
        component_width = candidate["component_width"]
        component_height = candidate["component_height"]
        right = left + component_width
        bottom = top + component_height
        white_pixels = 0
        white_min_x = width
        white_min_y = height
        white_max_x = -1
        white_max_y = -1
        if component_width > 0 and component_height > 0:
            for y in range(top, bottom):
                for x in range(left, right):
                    offset = (y * width + x) * 3
                    if _near(
                        pixels[offset],
                        pixels[offset + 1],
                        pixels[offset + 2],
                        (255, 255, 255),
                        36,
                    ):
                        white_pixels += 1
                        white_min_x = min(white_min_x, x)
                        white_min_y = min(white_min_y, y)
                        white_max_x = max(white_max_x, x)
                        white_max_y = max(white_max_y, y)
        white_width = (
            white_max_x - white_min_x + 1 if white_max_x >= white_min_x else 0
        )
        white_height = (
            white_max_y - white_min_y + 1 if white_max_y >= white_min_y else 0
        )
        component_area = component_width * component_height
        min_white_pixels = max(48, int(component_area * 0.0007))
        aspect = component_width / component_height if component_height else 0.0
        structured = (
            1.35 <= aspect <= 1.90
            and candidate["component_fill"] < 0.995
            and white_pixels >= min_white_pixels
            and white_width >= component_width * 0.18
            and white_height >= component_height * 0.05
        )
        candidate.update(
            {
                "component_aspect": aspect,
                "white_pixels": white_pixels,
                "white_width": white_width,
                "white_height": white_height,
                "threshold_white_pixels": min_white_pixels,
                "structured": structured,
            }
        )
        candidate["present"] = (
            candidate["component_pixels"] >= min_pixels
            and candidate["component_width"] >= min_width
            and candidate["component_height"] >= min_height
            and candidate["component_fill"] >= 0.40
            and structured
        )
        candidates[name] = candidate

    selected_name, selected = max(
        candidates.items(), key=lambda item: item[1]["component_pixels"]
    )
    return {
        "present": any(candidate["present"] for candidate in candidates.values()),
        "selected_color": selected_name,
        "threshold_pixels": min_pixels,
        "threshold_width": min_width,
        "threshold_height": min_height,
        "selected": selected,
        "colors": candidates,
    }


def _boot_logo_result(
    pixels: bytes,
    width: int,
    height: int,
    tolerance: int,
) -> dict[str, Any]:
    # Ignore the outer 4 percent so host window decorations cannot hide an
    # otherwise stale boot frame captured from the SDL client area.
    inset_x = int(width * 0.04)
    inset_y = int(height * 0.04)
    left = inset_x
    right = max(left + 1, width - inset_x)
    top = inset_y
    bottom = max(top + 1, height - inset_y)
    area = (right - left) * (bottom - top)
    counts = {name: 0 for name in BOOT_COLORS}
    mark_min_x = width
    mark_min_y = height
    mark_max_x = -1
    mark_max_y = -1

    for y in range(top, bottom):
        for x in range(left, right):
            offset = (y * width + x) * 3
            r, g, b = pixels[offset], pixels[offset + 1], pixels[offset + 2]
            matched_name = None
            for name, color in BOOT_COLORS.items():
                if _near(r, g, b, color, tolerance):
                    counts[name] += 1
                    matched_name = name
                    break
            if matched_name is not None and matched_name != "background":
                if x < mark_min_x:
                    mark_min_x = x
                if x > mark_max_x:
                    mark_max_x = x
                if y < mark_min_y:
                    mark_min_y = y
                if y > mark_max_y:
                    mark_max_y = y

    ratios = {name: count / area for name, count in counts.items()}
    palette_coverage = sum(counts.values()) / area
    mark_width = mark_max_x - mark_min_x + 1 if mark_max_x >= mark_min_x else 0
    mark_height = mark_max_y - mark_min_y + 1 if mark_max_y >= mark_min_y else 0
    if mark_width and mark_height:
        mark_center_x = (mark_min_x + mark_max_x + 1) / 2.0
        mark_center_y = (mark_min_y + mark_max_y + 1) / 2.0
        centered = (
            abs(mark_center_x - width / 2.0) <= width * 0.12
            and abs(mark_center_y - height / 2.0) <= height * 0.12
        )
    else:
        mark_center_x = 0.0
        mark_center_y = 0.0
        centered = False

    present = (
        palette_coverage >= 0.85
        and ratios["background"] >= 0.60
        and ratios["panel"] >= 0.025
        and ratios["title"] >= 0.0025
        and ratios["accent"] >= 0.001
        and mark_width >= width * 0.25
        and mark_height >= height * 0.07
        and mark_height <= height * 0.50
        and centered
    )
    return {
        "present": present,
        "palette_coverage": palette_coverage,
        "ratios": ratios,
        "mark_x": mark_min_x if mark_width else 0,
        "mark_y": mark_min_y if mark_height else 0,
        "mark_width": mark_width,
        "mark_height": mark_height,
        "mark_center_x": mark_center_x,
        "mark_center_y": mark_center_y,
        "mark_centered": centered,
    }


def _analyze(path: Path, sentinel_tolerance: int, boot_tolerance: int) -> dict[str, Any]:
    width, height, pixels = _load_image(path)
    return {
        "path": str(path),
        "width": width,
        "height": height,
        "pixel_sha256": hashlib.sha256(pixels).hexdigest(),
        "sentinel": _sentinel_result(pixels, width, height, sentinel_tolerance),
        "boot_logo": _boot_logo_result(pixels, width, height, boot_tolerance),
    }


def _write_receipt(path: Path, receipt: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n")
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--guest", required=True, type=Path)
    parser.add_argument("--host", required=True, type=Path)
    parser.add_argument("--receipt", type=Path)
    parser.add_argument("--sentinel-tolerance", type=int, default=18)
    parser.add_argument("--boot-tolerance", type=int, default=10)
    parser.add_argument(
        "--boot-logo-only",
        action="store_true",
        help="reject the xv6 boot logo without requiring the Qt sentinel",
    )
    args = parser.parse_args()
    if not 0 <= args.sentinel_tolerance <= 64:
        parser.error("--sentinel-tolerance must be between 0 and 64")
    if not 0 <= args.boot_tolerance <= 32:
        parser.error("--boot-tolerance must be between 0 and 32")

    try:
        guest = _analyze(args.guest, args.sentinel_tolerance, args.boot_tolerance)
        host = _analyze(args.host, args.sentinel_tolerance, args.boot_tolerance)
    except GateInputError as error:
        print(f"SDL-VISUAL-CONTENT-GATE ERROR reason=input-error detail={error}", file=sys.stderr)
        return 2

    reasons = []
    if guest["boot_logo"]["present"]:
        reasons.append("guest-boot-logo")
    if host["boot_logo"]["present"]:
        reasons.append("host-boot-logo")
    if not args.boot_logo_only:
        if not guest["sentinel"]["present"]:
            reasons.append("guest-sentinel-missing")
        if not host["sentinel"]["present"]:
            reasons.append("host-sentinel-missing")
    passed = not reasons
    receipt = {
        "status": "PASS" if passed else "FAIL",
        "reasons": reasons,
        "guest": guest,
        "host": host,
        "contract": {
            "boot_logo": "absent-from-both",
            "qt_wayland_sentinel": (
                "not-required" if args.boot_logo_only else "present-in-both"
            ),
            "sentinel_colors": {
                name: "#%02x%02x%02x" % color
                for name, color in SENTINEL_COLORS.items()
            },
        },
    }
    if args.receipt is not None:
        try:
            _write_receipt(args.receipt, receipt)
        except OSError as error:
            print(
                f"SDL-VISUAL-CONTENT-GATE ERROR reason=receipt-write detail={error}",
                file=sys.stderr,
            )
            return 2

    print(
        "SDL-VISUAL-CONTENT-GATE "
        f"status={receipt['status']} "
        f"reason={','.join(reasons) if reasons else 'sentinel-visible-in-both'} "
        f"guest_boot_logo={int(guest['boot_logo']['present'])} "
        f"host_boot_logo={int(host['boot_logo']['present'])} "
        f"guest_sentinel={int(guest['sentinel']['present'])} "
        f"host_sentinel={int(host['sentinel']['present'])} "
        f"guest_color={guest['sentinel']['selected_color']} "
        f"host_color={host['sentinel']['selected_color']}"
    )
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
