#!/usr/bin/env python3
"""
Host TCP stress server for xv6-os guest validation.

Listens on TCP <bind_addr>:<port>.  For each accepted connection it reads a
fixed 16-byte request header from the client and replies with a deterministic
payload of the requested size.

Wire protocol (little-endian, request only):
    uint32  magic  = 0xCA11AB1E
    uint32  conn_id   (echoed unchanged in the response header)
    uint32  payload_size
    uint32  pattern_seed

Response:
    uint32  magic  = 0x10AD0FAB
    uint32  conn_id
    uint32  payload_size
    uint32  pattern_seed
    bytes[payload_size] = pattern(pattern_seed)

Pattern is generated by a tiny xorshift32 keyed on pattern_seed so the guest
can validate it byte-for-byte without needing a shared random number generator.

The server delivers the response in many small write() chunks plus an
artificial pacing delay between chunks; this simulates a slow upstream HTTP
server and therefore exercises the lwIP receive window / netconn mailbox
hand-off on the guest side under back pressure.

Usage:
    tcpstress-host-server.py [--bind 0.0.0.0] [--port 5001]
                             [--chunk 4096] [--delay-ms 0]
                             [--max-conns 0]   # 0 == forever
                             [--quiet]
"""

import argparse
import functools
import socket
import struct
import sys
import threading
import time

REQ_MAGIC = 0xCA11AB1E
RSP_MAGIC = 0x10AD0FAB
HDR_FMT = "<IIII"
HDR_LEN = struct.calcsize(HDR_FMT)


@functools.lru_cache(maxsize=8)
def make_pattern(size: int, seed: int) -> bytes:
    """Deterministic xorshift32-based pseudorandom bytes (cached)."""
    if seed == 0:
        seed = 0xDEADBEEF
    state = seed & 0xFFFFFFFF
    out = bytearray(size)
    i = 0
    n = size
    while i + 4 <= n:
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= (state >> 17) & 0xFFFFFFFF
        state ^= (state << 5) & 0xFFFFFFFF
        state &= 0xFFFFFFFF
        out[i:i + 4] = state.to_bytes(4, "little")
        i += 4
    if i < n:
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= (state >> 17) & 0xFFFFFFFF
        state ^= (state << 5) & 0xFFFFFFFF
        state &= 0xFFFFFFFF
        tail = state.to_bytes(4, "little")
        out[i:n] = tail[: n - i]
    return bytes(out)


_print_lock = threading.Lock()


def log(quiet: bool, msg: str) -> None:
    if quiet:
        return
    with _print_lock:
        print(f"[tcpstress-host {time.strftime('%H:%M:%S')}] {msg}",
              flush=True)


def serve_one(sock: socket.socket, peer, chunk: int, delay_ms: float,
              quiet: bool) -> None:
    try:
        sock.settimeout(30.0)
        # Read request header (exact 16 bytes).
        hdr = b""
        while len(hdr) < HDR_LEN:
            data = sock.recv(HDR_LEN - len(hdr))
            if not data:
                log(quiet, f"{peer}: short header ({len(hdr)} bytes), drop")
                return
            hdr += data
        magic, conn_id, payload_size, seed = struct.unpack(HDR_FMT, hdr)
        if magic != REQ_MAGIC:
            log(quiet, f"{peer}: bad magic 0x{magic:08x}")
            return
        if payload_size > (64 << 20):
            log(quiet, f"{peer}: refusing oversize payload {payload_size}")
            return

        log(quiet,
            f"{peer}: conn_id={conn_id} payload={payload_size} "
            f"seed=0x{seed:08x} chunk={chunk} delay_ms={delay_ms}")

        rsp_hdr = struct.pack(HDR_FMT, RSP_MAGIC, conn_id, payload_size, seed)
        sock.sendall(rsp_hdr)

        body = make_pattern(payload_size, seed)
        view = memoryview(body)
        sent = 0
        delay_s = delay_ms / 1000.0
        while sent < payload_size:
            end = min(sent + chunk, payload_size)
            sock.sendall(view[sent:end])
            sent = end
            if delay_s > 0 and sent < payload_size:
                time.sleep(delay_s)
        log(quiet, f"{peer}: conn_id={conn_id} sent {sent} bytes OK")
    except Exception as exc:
        log(quiet, f"{peer}: error {exc!r}")
    finally:
        try:
            sock.shutdown(socket.SHUT_WR)
        except OSError:
            pass
        sock.close()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bind", default="0.0.0.0")
    ap.add_argument("--port", type=int, default=5001)
    ap.add_argument("--chunk", type=int, default=4096)
    ap.add_argument("--delay-ms", type=float, default=0.0)
    ap.add_argument("--max-conns", type=int, default=0,
                    help="exit after N connections served (0 = forever)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind((args.bind, args.port))
    srv.listen(256)
    log(args.quiet,
        f"listening on {args.bind}:{args.port} "
        f"(chunk={args.chunk} delay_ms={args.delay_ms} "
        f"max_conns={args.max_conns or 'inf'})")

    served = 0
    try:
        while True:
            client, peer = srv.accept()
            served += 1
            t = threading.Thread(target=serve_one,
                                 args=(client, peer, args.chunk,
                                       args.delay_ms, args.quiet),
                                 daemon=True)
            t.start()
            if args.max_conns and served >= args.max_conns:
                log(args.quiet,
                    f"max_conns={args.max_conns} reached, will exit "
                    f"once in-flight connections finish")
                break
    except KeyboardInterrupt:
        log(args.quiet, "SIGINT — shutting down")
    finally:
        srv.close()

    # Give worker threads a brief grace period.
    deadline = time.time() + 30.0
    for t in list(threading.enumerate()):
        if t is threading.current_thread() or not t.is_alive():
            continue
        remaining = max(0.0, deadline - time.time())
        t.join(timeout=remaining)

    log(args.quiet, f"done; served {served} connection(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
